// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreGraphics;
using Foundation;
using UIKit;

namespace Mailbox.iOS
{
	public partial class TableViewController : UITableView
	{

		public TableViewController (IntPtr handle) : base (handle)
		{			
		}

        public override void AwakeFromNib()
        {
            base.AwakeFromNib();
            this.Source = new MessageTableSource();
        }

    }

    public class MessageTableSource : UITableViewSource
    {
        EmailServer emailserver = new EmailServer();
        public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
        {
            UITableViewCell cell = new UITableViewCell(CGRect.Empty);
            var item = emailserver.Email[indexPath.Row];

            cell.TextLabel.Text = item.Subject;

            return cell;
        }

        public override nint RowsInSection(UITableView tableview, nint section)
        {
            return emailserver.Email.Count;
        }
    }
}
