// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Mailbox.iOS
{
	public partial class TableViewController : UITableView
	{
		public TableViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
